# This file is used to configure the copl dev environment. It is used to configure the build and hot-pod sections of the copl dev environment.

# The global offset for both sections is the copl bucket. Check the s3 bucket in the account to see the bucket.
#TODO The name format is copl-<account-id>-<region>. The bucket is used to store the build cache and the container image.
# The folder structure inside the bucket follows the format of this config file. 
remote:
#How long the environment will run
  ttl:
#Cloud provider name
  csp: aws
  instance:
  #instance type eg r5.2xlarge
    type: r5.2xlarge
# The build section is stored in the copl/build folder and the hot-pod section is stored in the copl/hot-pod folder.
build:
  # location of the build cache.It resides under the global copl bucket in a subfolder copl/build/cache
  cache:
    location: build/cache/dependencies.tar.gz
    # the location of the cache under the approot
    local: vendor/
# Hot pod is the app that is on the focus. This app runs in hot reloading mode and
# 1. runs the app from the pre-built directory
# 2. syncs the app source code directory with the local source code directory
hotPod:
# Warmup Job is in fact an init container that has virtually-all thesystem tools installed. 
# A nice sample scenario is If you want HotPod to wait until your db is ready and imports data,
# you can add a sleep here, then a mysql import.
  WarmUpJob:
# All your inbound and outboud traffic passes through this sidecar. It mis useful if you need 
# observability metrics, or FQDN overwrites, SSL termination.
  NetworkSidecar:
# Defines the name of app inside the helm chart
  helmValuesSection: bestApp
  image: 
    repository: myrepo
    tag: cuttingedge
  #Read the env vars from an .env file
  env-file:
  # hot pod overrides the commands in the container to run the copl-built app in the previous section
  commands: |
    cd /app-copl
    bundle install
    yarn install
